/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'companies': RouteRecordInfo<'companies', '/companies', Record<never, never>, Record<never, never>>,
    'control': RouteRecordInfo<'control', '/control', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'dashboard-crm-active-project': RouteRecordInfo<'dashboard-crm-active-project', '/dashboard/CrmActiveProject', Record<never, never>, Record<never, never>>,
    'dashboard-crm-activity-timeline': RouteRecordInfo<'dashboard-crm-activity-timeline', '/dashboard/CrmActivityTimeline', Record<never, never>, Record<never, never>>,
    'dashboard-crm-analytics-sales': RouteRecordInfo<'dashboard-crm-analytics-sales', '/dashboard/CrmAnalyticsSales', Record<never, never>, Record<never, never>>,
    'dashboard-crm-earning-reports-yearly-overview': RouteRecordInfo<'dashboard-crm-earning-reports-yearly-overview', '/dashboard/CrmEarningReportsYearlyOverview', Record<never, never>, Record<never, never>>,
    'dashboard-crm-order-bar-chart': RouteRecordInfo<'dashboard-crm-order-bar-chart', '/dashboard/CrmOrderBarChart', Record<never, never>, Record<never, never>>,
    'dashboard-crm-project-status': RouteRecordInfo<'dashboard-crm-project-status', '/dashboard/CrmProjectStatus', Record<never, never>, Record<never, never>>,
    'dashboard-crm-recent-transactions': RouteRecordInfo<'dashboard-crm-recent-transactions', '/dashboard/CrmRecentTransactions', Record<never, never>, Record<never, never>>,
    'dashboard-crm-revenue-growth': RouteRecordInfo<'dashboard-crm-revenue-growth', '/dashboard/CrmRevenueGrowth', Record<never, never>, Record<never, never>>,
    'dashboard-crm-sales-area-charts': RouteRecordInfo<'dashboard-crm-sales-area-charts', '/dashboard/CrmSalesAreaCharts', Record<never, never>, Record<never, never>>,
    'dashboard-crm-sales-by-countries': RouteRecordInfo<'dashboard-crm-sales-by-countries', '/dashboard/CrmSalesByCountries', Record<never, never>, Record<never, never>>,
    'dashboard-crm-sessions-bar-with-gap-charts': RouteRecordInfo<'dashboard-crm-sessions-bar-with-gap-charts', '/dashboard/CrmSessionsBarWithGapCharts', Record<never, never>, Record<never, never>>,
    'documentosdian': RouteRecordInfo<'documentosdian', '/documentosdian', Record<never, never>, Record<never, never>>,
    'documentosdian-notes': RouteRecordInfo<'documentosdian-notes', '/documentosdian/notes', Record<never, never>, Record<never, never>>,
    'documentosdian-payroll': RouteRecordInfo<'documentosdian-payroll', '/documentosdian/payroll', Record<never, never>, Record<never, never>>,
    'documentosdian-support': RouteRecordInfo<'documentosdian-support', '/documentosdian/support', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'inicio': RouteRecordInfo<'inicio', '/inicio', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'recepciondefacturas': RouteRecordInfo<'recepciondefacturas', '/recepciondefacturas', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
  }
}
